### ISSUE TITLE
Expose version as output

### ISSUE THREAD

**Issue by axelboc** [geritol/match-tag-to-package-version#2]
Hi! 👋 Thanks for this really convenient action 😄 

Would it be possible to expose the version number as an `output` of the action. This would save me from using a separate action to read the version from `package.json` again, like https://github.com/marketplace/actions/read-package-version.

**Comment by geritol** [comment]
Hi @axelboc sorry, did not see this.
PR and collaboration welcome on this!
Do you still need this feature and use the action?

**Comment by geritol** [comment]
@axelboc implemented and released in https://github.com/geritol/match-tag-to-package-version/releases/tag/0.1.0
Thanks for the feedback, I am happy that this little package provides value for you!

**Comment by axelboc** [comment]
>  Do you still need this feature and use the action?

Yes I do, thank you so much! 🚀
